default:
  image: gcc

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - make CONFIG_PAPIEX_PAPI=n CONFIG_PAPIEX_DEBUG=y
