default:
  image: centos:7

stages:      
  - build
#  - test

# Most of whats needed for the test suite
build:       
  stage: build
  script:
    - yum update -y
    - yum install -y gcc make file
    - yum install -y gcc-c++ gcc-gfortran perl python3
    - yum install -y tcsh bind-utils 
    - yum install -y tcl environment-modules git
    - make check
