# Always enable user mode access to events
#hooks:
#  script: echo 1 > /proc/sys/kernel/perf_event_paranoid

# Default GCC version
image: gcc:6.1

aliases:
 quicktest:
   script:
     - make quicktest
 debug:
   script:
     - DEBUG=1 make fulltest
 test:
   script:
     - make fulltest

 build: make -j2
