FROM mstormo/suse:latest

#RUN zypper --non-interactive --no-gpg-checks update
RUN zypper --non-interactive --no-gpg-checks install gcc make file tar gzip
RUN zypper --non-interactive install gcc-c++ gcc-fortran perl python3
RUN zypper --non-interactive install tcsh bind-utils openssh
RUN zypper --non-interactive clean -a

# SLES15 only has a python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install papiex and papiex tester
ARG release=papiex-epmt-2.0.0.tgz
WORKDIR /home
ADD ${release} /opt/epmt/
ADD test-${release} .
WORKDIR /home/tests
ENV PAPIEX_PREFIX=/opt/epmt/papiex-epmt-install

# Config SSH for testing
RUN mkdir /var/run/sshd
RUN echo -e "ForwardX11 no\nStrictHostKeyChecking no\nPreferredAuthentications publickey" >> /etc/ssh/ssh_config
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' 
RUN ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N "" && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys

# Configure two users with shitty csh and tcsh and allow root to login to them
RUN useradd -m -s /bin/csh -pfoo cshsucks && useradd -m -s /usr/bin/tcsh -pfoo tcshsucks
RUN mkdir ~cshsucks/.ssh  && cp ~/.ssh/authorized_keys ~cshsucks/.ssh/authorized_keys  && chmod 700 ~cshsucks/.ssh/  && chmod 600 ~cshsucks/.ssh/authorized_keys && chown -R cshsucks ~cshsucks/.ssh
RUN mkdir ~tcshsucks/.ssh && cp ~/.ssh/authorized_keys ~tcshsucks/.ssh/authorized_keys && chmod 700 ~tcshsucks/.ssh/ && chmod 600 ~tcshsucks/.ssh/authorized_keys && chown -R tcshsucks ~tcshsucks/.ssh

# Setup the environment, daemons and run the test script
RUN echo -e "#!/bin/bash\nmount -o remount rw /proc\nsysctl -w kernel.perf_event_paranoid=0\n/usr/sbin/sshd\nbash \$1" > /tmp/init.sh && chmod 755 /tmp/init.sh 
CMD ["/bin/bash","/tmp/init.sh","test.sh"]
