FROM rockylinux:8

WORKDIR /home
RUN yum update -y
RUN yum install -y gcc make file
RUN yum install -y gcc-c++ gcc-gfortran perl python3
RUN yum install -y tcsh bind-utils openssh-clients openssh-server
RUN yum install -y tcl environment-modules git

# Config SSH for testing
RUN mkdir /var/run/sshd
RUN echo -e "ForwardX11 no\nStrictHostKeyChecking no\nPreferredAuthentications publickey" >> /etc/ssh/ssh_config
# Generate SSH host keys without a passphrase for testing purposes only.
# This is acceptable in this controlled test environment as the image is not used in production.
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' 
RUN ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N "" && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys

# Configure two users with csh and tcsh shells and allow root to log in to them
RUN useradd -m -s /bin/csh -pfoo cshsucks && useradd -m -s /usr/bin/tcsh -pfoo tcshsucks
RUN mkdir ~cshsucks/.ssh  && cp ~/.ssh/authorized_keys ~cshsucks/.ssh/authorized_keys  && chmod 700 ~cshsucks/.ssh/  && chmod 600 ~cshsucks/.ssh/authorized_keys && chown -R cshsucks ~cshsucks/.ssh
RUN mkdir ~tcshsucks/.ssh && cp ~/.ssh/authorized_keys ~tcshsucks/.ssh/authorized_keys && chmod 700 ~tcshsucks/.ssh/ && chmod 600 ~tcshsucks/.ssh/authorized_keys && chown -R tcshsucks ~tcshsucks/.ssh

# Setup the environment, daemons and run the test script
RUN echo -e "#!/bin/bash\nmount -o remount rw /proc\nsysctl -w kernel.perf_event_paranoid=0\n/usr/sbin/sshd\n\$*" > /tmp/init.sh && chmod 755 /tmp/init.sh 
CMD ["/bin/bash","/tmp/init.sh","bash","test.sh"]

# Install papiex and papiex tester
ARG release=papiex-epmt-2.0.0.tgz
ADD ${release} /opt/epmt/
ADD test-${release} .
WORKDIR /home/tests
ENV PAPIEX_PREFIX=/opt/epmt/papiex-epmt-install

