name: compile_papiex                                                                                                                                                               
                                                                                                                                                                                        
on:                                                                                                                                                                                     
  push                                                                                                                                                                                  
                                                                                                                                                                                  
# cancel running jobs if theres a newer push                                                                                                                                            
concurrency:                                                                                                                                                                            
  group: ${{ github.workflow }}-${{ github.ref }}                                                                                                                                       
  cancel-in-progress: true                                                                                                                                                              
                                                                                                                                                                                        
                                                                                                                                                                                        
jobs:                                                                                                                                                                                   
  build-linux:                                                                                                                                                                          
    runs-on: ubuntu-latest                                                                                                                                                              
                                                                                                                                                                                        
    #service:                                                                                                                                                                           
    #  - postgres:latest                                                                                                                                                                
                                                                                                                                                                                        
    container:                                                                                                                                                                          
      image: rockylinux:8                                                                                                                                                               
      options: --privileged                                                                                                                                                             
                                                                                                                                                                                        
    steps:                                                                                                                                                                              
      - uses: actions/checkout@v4                                                                                                                                                       
      - name: yum install and update                                                                                                                                                    
        run: |                                                                                                                                                                          
          yum update -y                                                                                                                                                                 
          yum install -y findutils unzip bash tcsh nc curl make git gcc postgresql-devel zlib-devel bzip2 bzip2-devel readline-devel sqlite-devel openssl-devel xz xz-devel libffi-devel

      - name: install and configure sqlite3
        run: |
          cd /usr/src
          echo 'downloading sqlite3'
          curl -o sqlite-amalgamation-3490100.zip https://www.sqlite.org/2025/sqlite-amalgamation-3490100.zip
          unzip sqlite-amalgamation-3490100.zip
          echo 'building libsqlite3 with json1 and other useful extensions'
          cd sqlite-amalgamation-3490100
          gcc -shared -fPIC -O2  -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_MAX_VARIABLE_NUMBER=9999 sqlite3.c -o /usr/lib64/libsqlite3.so
                                                                                                                                                                                                                                                                                                                                           
      - name: install python3
        run: |
          cd /usr/src
          echo 'downloading python'
          curl -o Python-3.9.22.tgz https://www.python.org/ftp/python/3.9.22/Python-3.9.22.tgz
          # echo 'verifying checksum'
          # curl -o Python-3.9.22.tgz.asc https://www.python.org/ftp/python/3.9.22/Python-3.9.22.tgz.asc
          # sha256sum -c Python-3.9.22.tgz.asc || { echo 'Checksum verification failed!'; exit 1; }
          tar xzf Python-3.9.22.tgz
          cd Python-3.9.22
          echo 'building python3'
          ./configure --quiet --prefix=/usr --enable-shared --enable-optimizations --enable-loadable-sqlite-extensions
          make --silent install > /dev/null

      - name: configure python3 and upgrade pip and grab gcc-c++
        run: |
          ldconfig
          python3 -V
          pip3 install --upgrade pip
          yum install -y gcc-c++

      - name: make papiex                                                                                                                                               
        run: |                                                                                                                                                                          
          make OS_TARGET=rocky-8 distclean install dist                                                                                                                                

      - name: test papiex
        run: |
          make OS_TARGET=rocky-8 check
